### ISSUE TITLE
Shorthand null checking indents an extra unit

### ISSUE THREAD

**Issue by PenguinOwl** [rhysd/vim-crystal#100]
~~Minimum working example:~~ See below
```crystal
value : Int32 | Nil = 3

# expected:
if null_checked_value = value
  puts value + 2
  exit 0
end

# result:
if null_checked_value = value
    puts value + 2
  exit 0
end
```

**Comment by jlcrochet** [comment]
That's weird, I'm not getting this issue on HEAD. Can you confirm that you're on the latest version?

**Comment by PenguinOwl** [comment]
I'm on 0f08110, but AFAIK there haven't been any relevant changes since then.

**Comment by PenguinOwl** [comment]
Actually, I butchered the MWE too much. This is the issue:
```crystal
array = [0, 1, 2]

# expected
if null_checked_value = array[3]?
  puts value + 2
  exit 0
end

# result:
if null_checked_value = array[3]?
    puts value + 2
  exit 0
end
```
It occurs with any method ending in `?`, which is convention for methods that return null.

**Comment by rhysd** [comment]
I could reproduce this with HEAD.

1. Open scratch buffer and paste the following code to buffer
2. `:set ft=crystal`
3. Enter linewise visual mode with `V` and select lines from `if` to `end`
4. `=`

```
array = [0, 1, 2]

# expected
if null_checked_value = array[3]?
  puts value + 2
  exit 0
end
```

@jlcrochet Would you check if this occurs in your #98 branch? If it doesn't, your refactoring would solve this issue.

**Comment by jlcrochet** [comment]
@rhysd #98 would fix this, but I'm not sure when I'll be done with it. All I need to do is change one of the patterns, so I can submit a fix for that in the meantime.

**Comment by rhysd** [comment]
@jlcrochet Thank you. I merged the fix.
