### ISSUE TITLE
ECR files break formatting entirely until vim restart

### ISSUE THREAD

**Issue by PixeLInc** [rhysd/vim-crystal#105]
### Output of `vim --version` or `nvim --version`

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Steps to reproduce

1. Open a crystal file
2. Split open an ECR file
3. Try to format the crystal file
4. Close ECR file and try to format again

### Expected behavior
It should always format the CR file

### Actual behavior
It stops formatting the CR files 

### Additional information
This only happens if you open a crystal file first, then split an ECR file.
Upon closing the ECR file buffer, the formatter continues to be broken and is not usable until a vim restart.

No error occurs, or none visible at least.

**Comment by rhysd** [comment]
Please describe steps more specifically

> Close ECR file and try to format again

How did you format the buffer? There are two ways to apply formatter; auto formatting on save or running `:CrystalFormat` manually

**Comment by rhysd** [comment]
I could not reproduce this.

1. `nvim` in terminal
2. `:let g:crystal_auto_format = 1`
3. `:new foo.cr`
4. `:split foo.html.ecr`
5. `:close`
6. Modify buffer and `:w`

**Comment by rhysd** [comment]
I could reproduce this issue and fixed it. Please update this plugin to the latest.
