### ISSUE TITLE
Option to write buffer before executing spec

### ISSUE THREAD

**Issue by f1reflyyyylmao** [rhysd/vim-crystal#108]
When building projects with :make, I can set an option so the current buffer is saved automatically before executing the command. Could something similar be added to vim-crystal so my workflow goes from :w<return>gsa to just gsa?

**Comment by rhysd** [comment]
How about this?:

```vim
let g:crystal_define_mappings = 0
autocmd FileType crystal nmap <buffer>gsa :<C-u>w<CR><Plug>(crystal-spec-run-all)
```

This remaps `gsa` to write current buffer at first then run `:CrystalSpecRunAll`.

**Comment by f1reflyyyylmao** [comment]
While that would work out fine, I'd have to redefine all other keybinds as well. I'm not particularly satisfied with having yet another bunch of lines in my already humongous config, but I'd of course understand if you didn't want to add the shortcut to the plugin.

**Comment by rhysd** [comment]
Correct. Then how about removing `let g:crystal_define_mappings = 0`? `.vimrc` is loaded after plugins are loaded. So simply define `gsa` will overwrite the mapping defined by vim-crystal.
And `nnoremap` would be safer to avoid unexpected remapping.

```vim
autocmd FileType crystal nnoremap <buffer>gsa :<C-u>write | CrystalSpecRunAll<CR>
```

**Comment by f1reflyyyylmao** [comment]
Yes, that does the job. Please excuse my missing knowledge of vim, I'm still figuring things out :)
