### ISSUE TITLE
Support `crystal tool`

### ISSUE THREAD

**Issue by dlee** [rhysd/vim-crystal#15]
It looks like Crystal recently got support for method definition spelunking with its `crystal tool implementations`. It would be great if vim-crystal supported this.

http://crystal-lang.org/2015/09/05/tools.html

**Comment by rhysd** [comment]
Thank you for your pointing out.

Yeah I know the sub-command and I already add a task to my personal todo list.  I'll remain this issue open and will close when it is implemented.

**Comment by rhysd** [comment]
@dlee 

I implemented some features using `crystal tool`.

https://github.com/rhysd/vim-crystal#commands

Please try them!

@bcardiff @asterite

Thank you for nice tools!

**Comment by will** [comment]
This seems to work well in specs, but in my src directory it doesn't work. 

From their blog post:

> The crystal-tools atom package will use all the specs as main program. If this is not what you need to can change from the settings page which file to compile among other things.

What do you use as the main program? 

Also, thanks for making this plugin, I've been using it for a few months now, and it's been great!

**Comment by bcardiff** [comment]
FYI relevant crystal-atom-tools source https://github.com/manastech/atom-crystal-tools/blob/master/lib/crystal-tools.coffee#L101

**Comment by rhysd** [comment]
@will @bcardiff 

Thank you for pointing out.
This plugin uses the current buffer as main program for now, but current buffer may not be good for entry point...

**Comment by bcardiff** [comment]
Eventually there might be a descriptor or convention for main entry points inside a project. But, meanwhile, the all spec or current files or specified file seems to be good criteria.

**Comment by rhysd** [comment]
Hmm... I wander requiring all specs and current file is the most general.
What do you think, @bcardiff ?

**Comment by bcardiff** [comment]
@rhysd, that could work too. The case you will left outside is that if you are playing around in a sample without specs and the specs are failing to compile. But it does not seems to drastic.

So either a fixed configured file OR (current + all_specs) creating a temp file.

If there is no specs, the current file could be used directly.

So the thing atom-crystal would be missing is to include the current file [here](https://github.com/manastech/atom-crystal-tools/blob/master/lib/crystal-tools.coffee#L106)

That way if the current file is in /src/*\* but does not have specs the tools can still be runned.

I wonder what would be a good api to encapsulate this inside crystal itself... or if should be.

**Comment by rhysd** [comment]
@bcardiff 

Thank you for your explanation.

> So either a fixed configured file OR (current + all_specs) creating a temp file.

Only left case is that current file is in `src/` and no spec file corresponding to it doesn't exist.
If we assume that user introduces Test Driven Development, we need not to consider this case.
However, when user writes implementation at first and then writes the spec for it, vim-crystal doesn't work for the former...  (Of course I know that spec should be written before implementation, but some users may not do that.)

**Comment by will** [comment]
In situations where there aren't specs, the project is probably small enough that these tools aren't necessary, maybe.

A counter argument to that would be if you could be sent into the crystal stdlib source, but in my tests, it can't find that.

**Comment by bcardiff** [comment]
I expect the tooling be useful for playing with the language as a first comer so no specs in the first step is totally a scenario. A way to write code and get the idea of unions inside methods, navigate to std lib from invocations. Not only a demo driven thing, but could be used to explain things IMO.

Issue added :-)

**Comment by rhysd** [comment]
@will @bcardiff 

I agree that it is an edge case.  

Does requiring all specs (if exists) and current file together occur some problem (e.g. takes more time for compilation)?
If there is no problem,  I think requiring _all_ is better in terms of coverage of users' coding pattern.

**Comment by bcardiff** [comment]
The overhead should not be that much. 
It seems side effects are avoided. So I don't see any issue coming from double inclusion in case the file is included in the specs.

``` crystal
# file: puts_foo.cr
puts "foo"
{% puts "foo-compile" %}  # to check compile time passes.
```

``` crystal
# file: main.cr
require "./puts_foo"
puts "bar"
require "./puts_foo"
puts "baz"
```

```
$ crystal main.cr 
"foo-compile"
foo
bar
baz
$ crystal --version
Crystal 0.8.0 [e363b63] (Sat Sep 19 12:00:17 UTC 2015)

```

**Comment by rhysd** [comment]
@bcardiff 

Thank you for the codes.  I included both all specs and current file in 6b33e0f.  I'll test it tomorrow.

**Comment by rhysd** [comment]
I used this while developing [crdoc](https://github.com/rhysd/crdoc).  It seems to work well.  I'll close this issue again.

**Comment by will** [comment]
Thanks, @rhysd! Just checked it out now and it's working well for me too

**Comment by rhysd** [comment]
@will Thanks for your check :smile:
