### ISSUE TITLE
missing a highlighting of number literals with type suffixes

### ISSUE THREAD

**Issue by olehdevua** [rhysd/vim-crystal#17]
when I write

```
a = 43
```

then 43 is highlighted, but when I write

```
a = 43i32
b = 0x34f64
```

then the number literals is not highlighted

**Comment by rhysd** [comment]
It seems that literal suffixes remove underscores (e.g. `_u32` -> `u32`).  I'll fix them.

**Comment by rhysd** [comment]
I understood the behavior.
All of below are valid suffix...

``` crystal
0.1f64
0.1_f64
0.1__f64
0.1__________f64
```

**Comment by rhysd** [comment]
@OlegTsyba 

Looks good?

![screenshot](https://dl.dropboxusercontent.com/u/2753138/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202015-09-21%2016.42.35.png)

**Comment by olehdevua** [comment]
the trouble is that

```
1anychars
```

is now highlighted

**Comment by rhysd** [comment]
@OlegTsyba 

I limited suffixes to `i32`, `i64`, `f32`, `f64`, `u32` and `u64`.
Does it look good?

![ss](https://dl.dropboxusercontent.com/u/2753138/vim-crystal-issue17.png)

**Comment by olehdevua** [comment]
I think it works correctly now, thanks.
