### ISSUE TITLE
Syntax checking with syntastic

### ISSUE THREAD

**Issue by veelenga** [rhysd/vim-crystal#2]
It would be nice to highlight compile errors for crystal in vim. 

We can compile sources written in crystal with command and parse it's output:

```
$ crystal build filename.cr
```

First that comes to the mind is integration with [Syntastic](https://github.com/scrooloose/syntastic). Good example of such approach is [rust.vim](https://github.com/rust-lang/rust.vim).

Or we can supply it with syntastic directly. @rhysd, @scrooloose what can you say?

**Comment by rhysd** [comment]
Hi @veelenga.

Thank you for your suggestion.  But I'm not using syntastic and I don't know how to do that.
Could you send pull request?

I'm checking Crystal's syntax by writing quickrun setting manually [here](https://github.com/rhysd/dotfiles/blob/01a8da7b4c99398de7c6bfda25e8b59fb7b16065/vimrc#L2349-L2355)
Essentially, you can check the syntax by below command.

```
$ crystal run --no-build --nocolor {source.cr}
```

**Comment by veelenga** [comment]
Hi @rhysd. Thanks for quick reply.  Ok, I will send pull request soon.

**Comment by rhysd** [comment]
@veelenga 

Thanks!
BTW I think `errorformat` will be a bit complex and you can leave it empty.

**Comment by veelenga** [comment]
Unfortunately, without `errorformat` it will not work.
