### ISSUE TITLE
Automatic formatting

### ISSUE THREAD

**Issue by rhysd** [rhysd/vim-crystal#21]
Now Crystal compiler is planning to support formatting.

https://github.com/manastech/crystal/issues/309

After [`formatting` branch](https://github.com/manastech/crystal/tree/formatter) is merged into `master`, I should start to integrate it to vim-crystal.
- `:CrystalFmt` formats current buffer.
- On `BufWritePost`, automatically formats current buffer.  This behavior is controlled by `g:crystal_auto_format`.

**Comment by veelenga** [comment]
Happy to have it in vim-crystal! :+1:

**Comment by rhysd** [comment]
:muscle:

**Comment by sdogruyol** [comment]
:+1:

**Comment by rhysd** [comment]
Crystal 0.9.0 was released, which includes formatter :tada:.

**Comment by veelenga** [comment]
Cool. I have already used it :satisfied:. Can't wait integration with vim. Happy coding!

**Comment by will** [comment]
Thank you for quickly putting this in!

One problem I found with auto_format, it adds a space on my first require, but `crystal tool format` removes it.

```
crystal-pg ➤ vim src/pg.cr 
# then :wq right away

crystal-pg ➤ git diff
diff --git i/src/pg.cr w/src/pg.cr
index b4a8352..6229194 100644
--- i/src/pg.cr
+++ w/src/pg.cr
@@ -1,4 +1,4 @@
-require "./core_ext/*"
+ require "./core_ext/*"
 require "./pg/*"

 module PG
@@ -8,3 +8,4 @@ module PG
     conn
   end
 end
+

crystal-pg ➤ crystal tool format . 
Error: couldn't format './src/pg/libpq.cr', please report a bug including the contents of the file: https://github.com/manastech/crystal/issues
Format ./src/pg.cr

crystal-pg ➤ git diff
crystal-pg ➤
```

**Comment by rhysd** [comment]
Ah, thank you for the report, @will.

I'll open issue and check it.
