### ISSUE TITLE
two splits on same file problem

### ISSUE THREAD

**Issue by will** [rhysd/vim-crystal#24]
When I have my window split into two viewports on the same file, and then save in one viewport, the other viewport jumps to the beginning of the file, losing my place.

I think this is because of the auto formatting, but I'm not sure. 

Please let me know if you need any more information.

**Comment by rhysd** [comment]
Thank you for the report.  I could reproduce it.
1. Open Vim with Crystal code
2. Move to end with `G`.
3. `:vsplit`
4. `:CrystalFormat`

This is because vim-crystal replaces whole current buffer as below:
1. Get whole current buffer
2. Format by `crystal tool format`
3. Remove _entire_ current buffer
4. Paste formatted code

I must preserve the cursor positions of all buffers.

**Comment by rhysd** [comment]
@will 

This issue is fixed at least in my environment.
Could you also check it?

**Comment by will** [comment]
Thanks for looking at this. I can't check for a day or so, but will as soon as I can.

**Comment by rhysd** [comment]
It's OK when you have a time to check.

**Comment by will** [comment]
Sorry for taking so long, it's a little better thank you, but still the other pane moves on longer files

:e spec/pg/connection_spec.cr
:sp

move so top split starts at line 14, ends at 43, and cursor is on 40
move so bottom split start at line 75, ends at 104, and cursor on 105
:w on bottom split

bottom split stays put, but top split moves so is top at line 1 and bottom at line 30. When I move to the top split, the split moves so the cursor is still on line 40, by making the top line 11 and the bottom 40.

**Comment by rhysd** [comment]
Ah, OK, I'll check it later.  Thank you for the detail.

**Comment by rhysd** [comment]
Sorry for making you wait.  I tried.  It seems that cursor position is preserved but the screen position is not...
I'll try to fix it.

**Comment by rhysd** [comment]
@will 

At aebaadb, I confirmed that screen position is also fixed.  Could you check it?

**Comment by will** [comment]
Great! thank you!

**Comment by rhysd** [comment]
:+1:
