### ISSUE TITLE
Use crystal format

### ISSUE THREAD

**Issue by marceloboeira** [rhysd/vim-crystal#28]
I think it would be nice to have an options that enable the `crystal tools format`, triggered every time.

Mostly because of the standards that are going to be imposed by the language, such as, e.g.:

Before:

``` crystal
....
{ 
  foo: Int32,
  bar: String 
}
```

After change:

``` crystal
....
{ 
  foo: Int32,
  bar: String,
  another: String 
}
...
```

After formatter:

``` crystal
....
{ 
  foo:     Int32,
  bar:     String,
  another: String 
}
...
```

**Comment by rhysd** [comment]
Did you try `let g:crystal_auto_format = 1`?  It automatically formats current buffer on save.

**Comment by marceloboeira** [comment]
@rhysd I missed that! Thanks!
