### ISSUE TITLE
Determine initial mode (script|template) based on filename extension

### ISSUE THREAD

**Issue by paddor** [rhysd/vim-crystal#31]
I noticed that syntax highlighting is turned off up until the first `.template` directive when editing GSL scripts (`.gsl` files). If I'm understanding the [GSL documentation](https://github.com/imatix/gsl#toc4-1184) correctly, it depends on the filename given to `gsl`. So `.gsl` files start in script mode, `.xml` files start in template mode.

Not knowing much about Vimscript, let alone syntax highlighting rules, I poked around a bit in `gsl.vim` and found the following change to be helpful:

From:

``` vim
syn region gslDefaultMode start="^."                    keepend end="^\s*\.template\>"    contains=gslTemplModeDirectives
syn region gslTemplMode   start="^\s*\.template\s\+1\>" keepend end="^\s*\.endtemplate\>" contains=gslTemplModeDirectives
syn region gslScriptMode  start="^\s*\.template\s\+0\>" keepend end="^\s*endtemplate\>"   contains=gslScriptModeDirectives
```

To (change is at the **end of the first line**):

``` vim
syn region gslDefaultMode start="^."                    keepend end="^\s*\.template\>"    contains=gslScriptModeDirectives
syn region gslTemplMode   start="^\s*\.template\s\+1\>" keepend end="^\s*\.endtemplate\>" contains=gslTemplModeDirectives
syn region gslScriptMode  start="^\s*\.template\s\+0\>" keepend end="^\s*endtemplate\>"   contains=gslScriptModeDirectives
```

Now this works fine for me, since I don't usually edit template files (like `.xml` files). But I guess this change would negatively affect others. What's missing is a distinction of the filename extension of the currently open file.

Could somebody implement this? I guess it'd be enough if `.gsl` would mean "script mode", and anything else "template mode".

Thanks a lot.

**Comment by bew** [comment]
Excuse me, but how is this related to this project, vim-crystal ?

**Comment by paddor** [comment]
I'm very sorry, I think I meant to post this somewhere else.
