### ISSUE TITLE
First argument of fun declaration is incorrectly highlighted.

### ISSUE THREAD

**Issue by MatthewBennington** [rhysd/vim-crystal#38]
The following code is an excerpt from a Crystal shard, which binds to a C lib. The first function parameter should not be highlighted blue.
```

fun intrflush(win : WindowPtr, bool : Bool) : Int32
fun keypad(win : WindowPtr, bool : Bool) : Int32
fun mouseinterval(v : Int32) : Int32
fun mvwaddstr(win : WindowPtr, y : Int32, x : Int32, str : LibC::Char*) : Int32
fun newwin(rows : Int32, cols : Int32, y : Int32, x : Int32) : WindowPtr
```
<img width="585" alt="screen shot 2017-04-27 at 4 00 49 pm" src="https://cloud.githubusercontent.com/assets/14111207/25502132/66185f6e-2b63-11e7-8bb9-f5bfe3375b30.png">

**Comment by rhysd** [comment]
I addressed this issue at 8e113d7. Please update to the latest.
