### ISSUE TITLE
Be more specific in the readme installation section

### ISSUE THREAD

**Issue by Jens0512** [rhysd/vim-crystal#44]
A noob like me and many other don't find the [readme installation section](https://github.com/rhysd/vim-crystal#installation) specific enough.
Maybe something to copy-paste for the super-noobs?
Thank you for making this awesome plugin

**Comment by rhysd** [comment]
I feel the description seems enough. So could you tell me what is lack? (What 'more specific' means?)

**Comment by Jens0512** [comment]
Maybe just add something like `cp -R autoload ftdetect ftplugin indent plugin syntax ~/.vim/` (If i correctly understood what you meant)

Or full like 
`git clone https://github.com/rhysd/vim-crystal.git`
`cd vim-crystal`
`cp -R autoload ftdetect ftplugin indent plugin syntax ~/.vim/`
With an explanation

**Comment by rhysd** [comment]
Actual commands for installation looks good, although some commands are depending on the shell (i.e. cp -R would not work on Windows).

**Comment by rhysd** [comment]
I added. Thank you.
