### ISSUE TITLE
Faulty macro code syntax highlighting

### ISSUE THREAD

**Issue by Jens0512** [rhysd/vim-crystal#46]
As you can see the highlighting of the macro code in the interpolated string is weird.

![Example](https://user-images.githubusercontent.com/32913789/34727462-44ea3e5c-f557-11e7-8308-bab118777617.png)

**Comment by Jens0512** [comment]
Im not very experienced with regexes, but i'll give fixing it a go

**Comment by rhysd** [comment]
<img width="650" alt="スクリーンショット 2020-02-16 21 33 23" src="https://user-images.githubusercontent.com/823277/74604746-18710300-5104-11ea-8b47-dba388ddf97d.png">

Now it works fine. Thank you @Marzipanzerfaust for helping to fix this.
