### ISSUE TITLE
Problems with crystal tools and Syntastic

### ISSUE THREAD

**Issue by NIFR91** [rhysd/vim-crystal#47]
Hi, 

I can't use any crystal command like `:CrystalFormat` , `:CrystalDef`, etc.  Also there is no checking when running `:SyntasticCheck`

I installed vim-crystal with [Vundle Plugin](https://github.com/VundleVim/Vundle.vim)
using ` Plugin 'https://github.com/rhysd/vim-crystal.git'`. Im relative new to using vim so i need a little help to know what im doing wrong or if theres currently a problem with the pluggin. 

Im using  
```
Vim 
   VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 30 2017 18:21:38)

Crystal 
  Crystal 0.24.1 (2017-12-22)
  LLVM: 4.0.0
  Default target: x86_64-unknown-linux-gnu

OS 
  Debian GNU/Linux 9.3 (stretch) x86_64
```

an example of the erros I have when running `:CrystalDef` (gd) is:

```text
Error detected while processing /home/nieto/.vim/bundle/vim-crystal/autoload/cry
stal_lang.vim:
line    4:
E117: Unknown function: vital#crystal#new
E15: Invalid expression: vital#crystal#new()
line    5:
E121: Undefined variable: s:V
E15: Invalid expression: s:V.import('Process')
line    6:
E121: Undefined variable: s:V
E15: Invalid expression: s:V.import('ColorEcho')
analyzing definitions under cursor...
Error detected while processing function crystal_lang#jump_to_definition[3]..cry
stal_lang#impl[1]..crystal_lang#tool[14]..<SNR>101_run_cmd:
line    4:
E121: Undefined variable: s:P
E15: Invalid expression: s:P.system(a:cmd)

```

**Comment by rhysd** [comment]
I guess `vim-crystal/autoload/vital` directory is missing in your installation. How did you install vim-crystal?

**Comment by rhysd** [comment]
Could you please show the output of following commands?

```sh
$ cd ~/.bundle/vim
$ tree vim-crystal
```

**Comment by NIFR91** [comment]
Hi, 

I installed it using the pluging mannager [Vundle](https://github.com/VundleVim/Vundle.vim), adding 
the line `Plugin 'https://github.com/rhysd/vim-crystal.git'` in my `.vimrc`, and then running 
`:PluginInstall` in command mode of Vim.

The output if the commands 

```
cd ~/.vim/bundle/
tree vim-crystal 
```

is 

```
vim-crystal/
├── autoload
│   ├── crystal_lang.vim
│   └── vital
│       ├── _crystal
│       │   ├── ColorEcho.vim
│       │   ├── Data
│       │   │   ├── List.vim
│       │   │   └── String.vim
│       │   ├── Process.vim
│       │   └── Web
│       │       └── JSON.vim
│       ├── _crystal.vim
│       └── crystal.vital
├── ftdetect
│   └── crystal.vim
├── ftplugin
│   └── crystal.vim
├── indent
│   └── crystal.vim
├── plugin
│   └── crystal.vim
├── README.md
├── syntax
│   └── crystal.vim
└── syntax_checkers
    └── crystal
        ├── ameba.vim
        └── crystal.vim
```

**Comment by ceclinux** [comment]
my vim
```
vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec 19 2017 20:38:43)
1-1415
```
same error message and same tree structure

**Comment by rhysd** [comment]
Hm, nothing looks wrong... ok, I'll investigate further.

Could you try following command in Vim?

```
:call vital#crystal#new()
```

Does it also cause an error in your Vim?

**Comment by rhysd** [comment]
@ceclinux are you also using Vundle.vim?

**Comment by rhysd** [comment]
I've found the reason. I forgot adding one more file to load some libraries. I'll fix this soon.

**Comment by rhysd** [comment]
@NIFR91 @ceclinux I fixed this at 71a14b9. Please update to the latest. I'm sorry for inconvenience.

**Comment by NIFR91** [comment]
@rhysd Thanks. 
 
After update everything is working ( `:Crystal` commands and Syntastic ) :smile: . 

Great plugging :heart:

**Comment by ceclinux** [comment]
@rhysd  good job, works after fix 👍
