### ISSUE TITLE
Syntax highlighting fails with backtick character literal

### ISSUE THREAD

**Issue by LVMBDV** [rhysd/vim-crystal#49]
![20180228004934](https://user-images.githubusercontent.com/17510795/36756973-9364b5b2-1c21-11e8-8d26-a8cb0b69e719.png)

A simpler example to reproduce it would be:

```crystal
puts '`' # oh no
```

**Comment by rhysd** [comment]
@LVMBDV I addressed this at 7536fb5. Please update to the latest.

**Comment by LVMBDV** [comment]
Thanks for the quick response :)
