### ISSUE TITLE
Wrong spec_helper path for nested specs

### ISSUE THREAD

**Issue by sudo-nice** [rhysd/vim-crystal#51]
Consider the following project structure:

```
.
├── spec
│  └── spec_helper.cr
└── src
   ├── foo
   │  └── bar.cr
   └── foo.cr
```

Now, if we open `foo.cr` end execute `:CrystalSpecSwitch`, we will correctly get the into `foo_spec.cr` with correct first line: `require "./spec_helper"`.
But if we open `bar.cr` end execute `:CrystalSpecSwitch`, we will correctly get into `bar_spec.cr` and the require line will be again `require "./spec_helper"`, but it rather should be `require "../spec_helper"`. What do you think?

**Comment by rhysd** [comment]
Let me clarify actual sequence to reproduce this.

0. `spec/foo/bar_spec.cr` does not exist (is this correct?)
1. Open `src/foo/bar.cr` with `:edit`
2. Run `:CrystalSpecSwitch` with no argument
3. `spec/foo/bar_spec.cr` is opened

In the case, vim-crystal did not insert the `require "./spec_helper"`. It just opened the file with `:edit!` (if a target file does not exist, it just opens an empty buffer). I guess you're using some other template plugin which inserts the wrong `require "./spec_helper"` line automatically. This is not a problem of vim-crystal.

**Comment by sudo-nice** [comment]
>I guess you're using some other template plugin which inserts the wrong require "./spec_helper" line automatically.

You are completely right, that line was added by [vim-eunuch](https://github.com/tpope/vim-eunuch).
Thank you very much!
