### ISSUE TITLE
Incorrect indentation for private classes

### ISSUE THREAD

**Issue by Helloman892** [rhysd/vim-crystal#59]
What it should look like:
```crystal
private class R
  def initialize
  end
end
```
What it ends up looking like (`gg=G`):
```crystal
private class R
def initialize
end
end
```
Upon experimentation, it seems to me that the indentation level isn't increased after a `private class` declaration. I'm sadly no Vim syntax highlighting wizard, so I haven't been able to thunk a fix.

**Comment by rhysd** [comment]
Thank you for reporting this. 928ce1e should address this. Please update this plugin to the latest.

**Comment by Helloman892** [comment]
I found this solution myself, and ran into two issues:
First, the deindent rule doesn't include the keywords - so `end` won't match correctly:
```crystal
module T
  private class R
    def k
    end
end
end
```
Secondly, `private abstract` et al. are legal, and aren't covered by this new rule.

**Comment by rhysd** [comment]
ok, thank you for your confirmation. It's very helpful

**Comment by rhysd** [comment]
And I found `public` is not a keyword actually...

**Comment by rhysd** [comment]
@Helloman892 How about 90fed75 and a10aa6b? I confirmed your example was indented fine by them:

```crystal
module T
  private class R
    def k
    end
  end
end
```

**Comment by Helloman892** [comment]
Yes, this seems to fix the problem. Thanks for your prompt response!
