### ISSUE TITLE
Problem with NERDTree

### ISSUE THREAD

**Issue by basmoura** [rhysd/vim-crystal#6]
Hey, nice job with vim-crystal, i figured out about crystal-lang yesterday and the first think that i looked for was the plugin for vim.

So, my NERDTree became weird after the vim-crystal. The problem is, when I open the vim for the first time its normal, then I open a .cr file and the colours of the NERDTree still normal. The problem begins when I close the .cr file and open another .cr, the NERDTree loses all the colours and became green.

When I open the for the first time
![screen shot 2015-07-27 at 9 55 36 am](https://cloud.githubusercontent.com/assets/3411986/8906582/417a0e20-3446-11e5-80de-a848645b2439.png)

When i close the file and open another
![screen shot 2015-07-27 at 9 56 05 am](https://cloud.githubusercontent.com/assets/3411986/8906583/417f3792-3446-11e5-8308-c38d61def706.png)

**Comment by rhysd** [comment]
Hi, @basmoura .

Thank you for your report.

I actually don't use nerdtree.  So I tried it in minimum environment.

``` sh
$ mkdir tmp && cd tmp
$ git clone https://github.com/scrooloose/nerdtree.git
$ git clone https://github.com/rhysd/vim-crystal.git
```

And I wrote very small vimrc as `tmp.vimrc`.

``` vim
set nocompatible
set rtp+=./nerdtree
set rtp+=./vim-crystal

syntax enable
colorscheme desert
```

Then I started vim.

``` sh
$ vim -u tmp.vimrc
```

After that, I executed `:NERDTreeToggle` and opened crystal code, closed it and opened second crystal code.
Finally I could reproduce the collapsed syntax highlight :tada:

**Comment by rhysd** [comment]
@basmoura 

The reason is that the filetype of NERDTree buffer is set to `crystal`.
<del>I think this is an issue of NERDTree on opening a file without an empty buffer because vim-crystal is a very simple filetype plugin.</del><br>

<del>Could you report this bug to NERDTree issues with this page's URL?  I think NERDTree developer can solve the problem.</del>

**Comment by rhysd** [comment]
@basmoura 

I found a bug on filetype detection in vim-crystal.  I fixed it in 6d69504.  At least the bug was fixed in my test environment.
Could you update vim-crystal and test it?  If test is OK, I'll close this issue.

**Comment by basmoura** [comment]
@rhysd works perfectly :tada: 

thank you, nice job man!

**Comment by rhysd** [comment]
@basmoura 

Thanks for your confirmation!
