### ISSUE TITLE
Can't get omnicompletion to work

### ISSUE THREAD

**Issue by vushu** [rhysd/vim-crystal#63]
Hi there thanks for the plugin. but i cant seem to get the omnicompletion to work

I just installed it using Plug 'rhysd/vim-crystal'

when pressen `<C-X><C-O>` nothing happens, but it seems like the other functions are working
like, do I need to install other dependencies?

**Comment by rhysd** [comment]
Today I confirmed completion works fine on my local. I didn't install any other additional tools than `crystal` command.

![tmp](https://user-images.githubusercontent.com/823277/103463468-eabe9800-4d6f-11eb-8def-68d6b43b2dcd.gif)

As described in README.md, the completion uses `crystal tool context` command hence it only supports to complete variables. If you want more advanced completion, please consider to use langauge servers like [crystalline](https://github.com/elbywan/crystalline).

**Comment by TangMonk** [comment]
> Today I confirmed completion works fine on my local. I didn't install any other additional tools than `crystal` command.

How to use with crystalline? and how about [Scry](https://github.com/crystal-lang-tools/scry)?

**Comment by rhysd** [comment]
Please use your favorite LSP client plugin.

**Comment by asnewman** [comment]
I also cannot get omni complete working (I'm an omni complete noob). Is there anything I need set up in my vimrc for it to autocomplete?

https://user-images.githubusercontent.com/15795866/184066242-0addd53d-9d5c-40a5-b2fc-06cd81e9e80b.mov
