### ISSUE TITLE
Support to collapse / fold

### ISSUE THREAD

**Issue by xqyww123** [rhysd/vim-crystal#64]
Hi, `vim-crystal` is great and I love it. But when I trying to collapse(fold) my code using `syntax` mode, I mean the way described [here](https://vim.fandom.com/wiki/Folding) with configuration like:

    set foldmethod=syntax

I found it doesn't work at all. While the default `indent` mode doesn't work well, actually a way is absent to collapse Crystal code in Vim. 

I love Vim and Crystal and thus this script, hoping the feature comes true one day.

**Comment by rhysd** [comment]
Resolved by #72.
