### ISSUE TITLE
Auto format should not block saving buffer

### ISSUE THREAD

**Issue by willhbr** [rhysd/vim-crystal#79]
Currently, if the buffer has a syntax error it is impossible to save it if `g:crystal_auto_format` is set. This means you can't save your file to run the compiler to see what the error was.

I can get this behaviour by replacing the `throw` in `crystal_lang#format_string` with a `return a:code` but I'm fairly sure there is a better way of doing this (since I don't really know vimscript).

Thanks!

**Comment by rhysd** [comment]
Thank you for reporting this. I think file should be saved even if error message is shown. I'll try to make it better.

**Comment by rhysd** [comment]
With 31db50d, a buffer is saved even if formatting fails.

**Comment by willhbr** [comment]
Thanks for fixing this! ☺️
