### ISSUE TITLE
Syntax: regression in highlighting 'end'

### ISSUE THREAD

**Issue by sudo-nice** [rhysd/vim-crystal#80]
None of the `end`s is highlighted for this code?

```crystal
class Hello
  def foo
    bar do
      baz << 1
    end #<- here
  end   #<- here
end     #<- here
```

Git bisect blames the commit ef347697da2604cf1c5b9f1066b1bb8983458f3b

**Comment by rhysd** [comment]
I confirmed #81 fixed this issue. Thank you @Marzipanzerfaust for the fix and thank you @sudo-nice for reporting this.
