### ISSUE TITLE
Regression in highlighting until...end

### ISSUE THREAD

**Issue by sudo-nice** [rhysd/vim-crystal#87]
Please, consider the snippet:

```crystal
def foo
  until true
    do_something
  end # <- wrong highlighting
end   # <- wrong highlighting
```
The same wrong highlighting happens for `while` block.

Git bisect blames the commit d2061b2ddbf2c57fae63f91ba710dee764c5cbcf

**Comment by rhysd** [comment]
I confirmed #86 fixed this issue. Thank you @jlcrochet for fixing this and thank you @sudo-nice for reporting this.
