### ISSUE TITLE
Invalid argument: crystalExceptional

### ISSUE THREAD

**Issue by MrSorcus** [rhysd/vim-crystal#93]
```text
Error detected while processing /home/user/.local/share/nvim/plugged/vim-crystal/syntax/crystal.vim:
line  314:
E871: (NFA regexp) Can't have a multi follow a multi
E475: Invalid argument: crystalExceptional       "\<\%(\%(;\|^\)\s*\@<=rescue\|else\|ensure\)\>[?!]\@!" contained containedin=crystalBlockExpression
Press ENTER or type command to continue
```
Problem commit is 7d235e38ca454e9bdbac3106798685661a625937

**Comment by rhysd** [comment]
Would you tell me value of 'regexpengine' option?

**Comment by jlcrochet** [comment]
This is my bad: the pattern should be `"\<\%(\%(\%(;\|^\)\s*\)\@<=rescue\|else\|ensure\)\>[?!]\@!"`. I must have forgotten to fix that in my previous commit.

**Comment by rhysd** [comment]
Thank you for your quick check. Would you make a PR?
