### ISSUE TITLE
Move to organization

### ISSUE THREAD

**Issue by rhysd** [rhysd/vim-crystal#99]
Recently I'm not so active user of Crystal though I still maintain a few Crystal projects. To make it easy to improve this plugin, I'm considering to move this plugin to `vim-crystal` organization.

I continue to maintain this plugin after moving to org. And considering many and continuous contributions, I'm willing to invite @jlcrochet as maintainer. @jlcrochet, what do you think? Maintainer can add commits without review (of course making PR is also welcome for reviews by other maintainers).

If someone wants to join as maintainer, please let me know in this issue. Requirements for maintainers are:

- familiar with Vim script and Crystal
- have contributed to this plugin at least once (it means listed in [contributors](https://github.com/rhysd/vim-crystal/graphs/contributors))

**Comment by jlcrochet** [comment]
Sure, I would be happy to. I would still prefer to run PR's by you if you have the time to review them, so I don't think much will really change in that regard.

**Comment by bew** [comment]
What about moving it to the [`crystal-lang-tools`](https://github.com/crystal-lang-tools) organization?

Related #39

**Comment by rhysd** [comment]
> Sure, I would be happy to. I would still prefer to run PR's by you if you have the time to review them, so I don't think much will really change in that regard.

Thank you. Of course making PR is ok. Please add me to reviewers.

> What about moving it to the crystal-lang-tools organization?

Thanks for the suggestion. I thought the idea but I preferred moving to new org like vim-ruby/vim-ruby.

If vim-crystal joins crystal-lang-tools org,

- Cons
  - I don't have control of the org. For example, I would not be able to add more maintainers freely. (I need to ask administrator of the org to add new people) It looks additional management cost for me.
  - More people than necessary have write access to vim-crystal repo. I want to keep the number of people who have write access as small as possible for security reason. More people having write access means more security risks (e.g. account hacking). As you know, Vim plugin model is very vulnerable. Users of Vim plugin must trust the plugin entirely.
- Pros
  - Actually I'm not seeing any pros about gathering editor supports to one organization. Beginners would google with query like 'vim crystal language' and can easily reach this plugin even if this plugin is hosted in a dedicated organization.

**Comment by bew** [comment]
Good points, I understand

**Comment by rhysd** [comment]
@jlcrochet I sent you an invitation.
